// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Supabase connection pooler (포트 6543)에서 prepared statement 충돌 방지
    // Migrations/Push 작업은 direct connection (포트 5432) 사용
    url: env('DIRECT_URL') || env('DATABASE_URL'),
  },
});
